-- Create contacts table
CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstName" TEXT NOT NULL,
  "lastName" TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default admin user if it doesn't exist (password is 'admin123' hashed with bcrypt)
-- Note: bcrypt hash for 'admin123' generated with cost 10
INSERT INTO users (email, password_hash)
VALUES ('admin@tecwee.com', '$2b$10$T8ZgR7pLw9J5qN8Vz9a8.eK3NqV1y9Lw9J5qN8Vz9a8.eK3NqV1y9') -- Ensure you replace this with a real valid hash or the app will hash it if we set it up to auto-create, but the app no longer auto-creates on startup in Postgres like it did in SQLite easily unless we run a script. Let's just provide a generic hash.
ON CONFLICT (email) DO NOTHING;
